---
settings:
  name: Kubernetes clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr
sidebar:
  entries:
  - title: 所有Cloud Manager文件
    url: https://docs.netapp.com/us-en/cloud-manager-family
  - title: Kubernetes文件
    url: "/index.html"
  - title: 版本資訊
    url: "/whats-new.html"
  - title: 開始使用
    entries:
    - title: 瞭解Kubernetes資料管理
      url: "/concept-kubernetes.html"
    - title: 快速入門
      url: "/task/task-k8s-quick-start.html"
  - title: 需求
    entries:
    - title: AWS上的Kubernetes叢集
      url: "/requirements/kubernetes-reqs-aws.html"
    - title: Azure上的Kubernetes叢集
      url: "/requirements/kubernetes-reqs-aks.html"
    - title: Google Cloud上的Kubernetes叢集
      url: "/requirements/kubernetes-reqs-gke.html"
  - title: 新增Kubernetes叢集
    entries:
    - title: 在AWS上新增叢集
      url: "/task/task-kubernetes-discover-aws.html"
    - title: 在Azure上新增叢集
      url: "/task/task-kubernetes-discover-azure.html"
    - title: 在Google Cloud上新增叢集
      url: "/task/task-kubernetes-discover-gke.html"
  - title: 管理Kubernetes叢集
    url: "/concept-manage-k8s.html"
    entries:
    - title: 安裝Astra Trident
      url: "/task/task-k8s-manage-trident.html"
    - title: 管理儲存類別
      url: "/task/task-k8s-manage-storage-classes.html"
    - title: 檢視持續磁碟區
      url: "/task/task-k8s-manage-persistent-volumes.html"
    - title: 移除叢集
      url: "/task/task-k8s-manage-remove-cluster.html"
    - title: 啟用NetApp雲端資料服務
      url: "/task/task-kubernetes-enable-services.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/support/task-support-registration.html"
    - title: 取得協助
      url: "/support/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 瞭解Kubernetes資料管理
      url: "/concept-kubernetes.html"
    - title: 快速入門
      url: "/task/task-k8s-quick-start.html"
  - title: 需求
    links:
    - title: AWS上的Kubernetes叢集
      url: "/requirements/kubernetes-reqs-aws.html"
    - title: Azure上的Kubernetes叢集
      url: "/requirements/kubernetes-reqs-aks.html"
    - title: Google Cloud上的Kubernetes叢集
      url: "/requirements/kubernetes-reqs-gke.html"
  - title: 新增Kubernetes叢集
    links:
    - title: 在AWS上新增叢集
      url: "/task/task-kubernetes-discover-aws.html"
    - title: 在Azure上新增叢集
      url: "/task/task-kubernetes-discover-azure.html"
    - title: 在Google Cloud上新增叢集
      url: "/task/task-kubernetes-discover-gke.html"
  - title: 管理Kubernetes叢集
    links:
    - title: 安裝Astra Trident
      url: "/task/task-k8s-manage-trident.html"
    - title: 管理儲存類別
      url: "/task/task-k8s-manage-storage-classes.html"
    - title: 檢視持續磁碟區
      url: "/task/task-k8s-manage-persistent-volumes.html"
    - title: 移除叢集
      url: "/task/task-k8s-manage-remove-cluster.html"
    - title: 啟用資料服務
      url: "/task/task-kubernetes-enable-services.html"
  - title: 取得Cloud Manager的協助
    links:
    - title: 註冊以取得支援
      url: "/support/task-support-registration.html"
    - title: 取得協助
      url: "/support/task-get-help.html"
  - title: 部落格社群
    links:
    - title: NetApp社群
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central部落格
      url: https://cloud.netapp.com/blog
    - title: 雲端網路研討會
      url: https://cloud.netapp.com/events
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
